name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like River to do?
    validations:
      required: true
  - type: textarea
    id: privacy
    attributes:
      label: Privacy considerations
      description: Would this require the server to learn anything new about users?
